/**
 * KRODEX API — Phase 8 action proposal store.
 *
 * The proposal store is the *only* place that holds a pending
 * mutation the AI suggested. Per PRD §33, TRD §21, and
 * Implementation Plan §334–342:
 *
 *   - The AI never writes to the database. It returns a
 *     `proposal` block as part of the assistant response. The
 *     orchestrator (`assistant-service.ts`) replaces the
 *     model-supplied id and `createdAt` with server-generated
 *     values, then stores the proposal here.
 *   - The student explicitly confirms or rejects on the next
 *     round-trip. The confirm endpoint calls back into this
 *     store via `lookupProposal`. On confirm, the orchestrator
 *     returns the proposal so the route can dispatch it to
 *     the matching domain service (planner / review). On
 *     reject, the proposal is removed.
 *   - Each proposal has a 30-minute TTL. Expired entries are
 *     invisible to `lookupProposal` so a stale confirm
 *     returns 404 instead of executing a mutation the student
 *     no longer expects.
 *
 * The store is a per-process `Map<userId, Map<proposalId,
 * Entry>>`. The single-process scope is the Phase 8 limit
 * (per the approved plan, no Redis). A future phase can
 * back this with a shared store without changing the
 * public surface (`storeProposal`, `lookupProposal`,
 * `deleteProposal`).
 */

import type { AssistantProposalT } from './schemas';

const PROPOSAL_TTL_MS = 30 * 60 * 1000; // 30 minutes

interface StoredProposal {
  readonly proposal: AssistantProposalT;
  readonly storedAt: number;
}

const store: Map<string, Map<string, StoredProposal>> = new Map();

/**
 * Place a proposal under the calling user. The proposal's
 * `id` MUST have been generated by the server (see
 * `makeProposalId` in `assistant-service.ts`); the caller
 * is responsible for replacing any model-supplied id.
 */
export function storeProposal(
  userId: string,
  proposal: AssistantProposalT,
  now: () => Date = () => new Date(),
): void {
  const ttl = now().getTime();
  let bucket = store.get(userId);
  if (!bucket) {
    bucket = new Map();
    store.set(userId, bucket);
  }
  bucket.set(proposal.id, { proposal, storedAt: ttl });
}

/**
 * Look up a proposal by id, scoped to the calling user. An
 * expired entry (older than `PROPOSAL_TTL_MS`) is treated as
 * not found so the route returns 404 instead of executing
 * a stale mutation.
 */
export function lookupProposal(
  userId: string,
  proposalId: string,
  now: () => Date = () => new Date(),
): AssistantProposalT | null {
  const bucket = store.get(userId);
  if (!bucket) return null;
  const entry = bucket.get(proposalId);
  if (!entry) return null;
  const ageMs = now().getTime() - entry.storedAt;
  if (ageMs > PROPOSAL_TTL_MS) {
    bucket.delete(proposalId);
    return null;
  }
  return entry.proposal;
}

/**
 * Remove a proposal from the store. Used when the student
 * explicitly rejects the proposed mutation, and internally
 * when an entry expires.
 */
export function deleteProposal(userId: string, proposalId: string): void {
  const bucket = store.get(userId);
  if (!bucket) return;
  bucket.delete(proposalId);
  if (bucket.size === 0) {
    store.delete(userId);
  }
}

/**
 * Test seam — clears the in-process store. Production code
 * never invokes this; tests do to keep state isolated.
 */
export function _resetProposalStoreForTests(): void {
  store.clear();
}

export const PROPOSAL_TTL = PROPOSAL_TTL_MS;
